import { base64Url } from './capability';

const PERMISSIONS_POLICY = 'accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-create=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), web-share=(), xr-spatial-tracking=()';

export function bridgeResponse(hostname: string, bootstrapToken: string, carrierMode: 'websocket' | 'websocket-lanes' = 'websocket'): Response {
  const nonce = base64Url(crypto.getRandomValues(new Uint8Array(18)));
  const origin = `https://${hostname}`;
  const body = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connection</title></head><body><script nonce="${nonce}">
(()=>{'use strict';const relayOrigin=${JSON.stringify(origin)};const bootstrap=${JSON.stringify(bootstrapToken)};const carrierMode=${JSON.stringify(carrierMode)};
const fragment=location.hash,androidNonce=/^#android=([A-Za-z0-9_-]{43})$/.exec(fragment)?.[1]||'';history.replaceState(null,'',location.pathname);
let initialized=false,closed=false,port=null,sessionToken='',socket=null,creating=false;const queued=[];let queuedBytes=0,upTimer=0;const lanes=new Map(),closedLanes=new Set(),closedLaneOrder=[],laneQueueLimit=8388608,laneItemLimit=1024;const queueLimit=33554432,batchLimit=524288,batchFrames=4096,coalesceAt=262144;
function splitFrames(value){const view=new DataView(value);let offset=0,result=[];while(offset<value.byteLength){if(value.byteLength-offset<8||result.length>=4096)throw 0;const size=view.getUint32(offset+4),end=offset+8+size;if(size>1048576||end>value.byteLength)throw 0;result.push(value.slice(offset,end));offset=end}if(!result.length)throw 0;return result}
const status=state=>{if(port&&!closed)port.postMessage({t:'status',state})};
const opts=(method,token,body,keepalive=false)=>({method,body,keepalive,mode:'same-origin',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:Object.assign(token?{Authorization:'Bearer '+token}:{},body?{'Content-Type':'application/octet-stream'}:{})});
function fail(){if(closed)return;status('failed');if(port)port.postMessage({t:'close'});shutdown(true)}
function splitFrames(value){const view=new DataView(value),result=[];let offset=0;while(offset<value.byteLength){if(value.byteLength-offset<8||result.length>=4096)throw 0;const size=view.getUint32(offset+4),end=offset+8+size;if(size>1048576||end>value.byteLength)throw 0;result.push({type:view.getUint8(offset),id:(view.getUint8(offset+1)<<16)|(view.getUint8(offset+2)<<8)|view.getUint8(offset+3),data:value.slice(offset,end)});offset=end}return result}
function laneBuffered(){let total=0;for(const lane of lanes.values())if(lane.socket&&lane.socket.readyState===WebSocket.OPEN)total+=lane.socket.bufferedAmount+lane.bytes;return total}
function rememberLaneClosed(id){if(closedLanes.has(id))return;if(closedLaneOrder.length===4096)closedLanes.delete(closedLaneOrder.shift());closedLanes.add(id);closedLaneOrder.push(id)}
function closeFrame(id){const data=new ArrayBuffer(8),view=new DataView(data);view.setUint8(0,3);view.setUint8(1,id>>>16);view.setUint8(2,id>>>8);view.setUint8(3,id);return data}
function finishLane(lane,notify){if(lane.finished||lanes.get(lane.id)!==lane)return;lane.finished=true;if(lane.timer)clearTimeout(lane.timer);lane.pending.length=0;lane.bytes=0;lane.items=0;lanes.delete(lane.id);rememberLaneClosed(lane.id);if(lane.socket)try{lane.socket.close()}catch{};if(notify&&!closed){const frame=closeFrame(lane.id);port.postMessage(frame,[frame])}}
function openLane(lane){const socket=new WebSocket(relayOrigin.replace(/^https:/,'wss:')+'/api/v1/ws','tproxy-lane-v1.'+sessionToken+'.'+lane.id);lane.socket=socket;socket.binaryType='arraybuffer';socket.onopen=()=>{if(closed||lane.finished)return socket.close();lane.opened=true;status('connected');runLaneUp(lane)};socket.onmessage=event=>{if(!(event.data instanceof ArrayBuffer)||!event.data.byteLength)return fail();let values;try{values=splitFrames(event.data)}catch{return fail()}if(values.some(value=>value.id!==lane.id))return fail();if(values.some(value=>value.type===3))lane.remoteClosed=true;port.postMessage({t:'traffic',up:0,down:event.data.byteLength});port.postMessage(event.data,[event.data])};socket.onerror=()=>{};socket.onclose=()=>{if(closed||lane.finished)return;if(!lane.opened)return fail();finishLane(lane,!lane.localClosed&&!lane.remoteClosed)}}
function queueLane(value){let lane=lanes.get(value.id);if(!lane&&(value.type===2||value.type===3||value.type===4))return;if(!value.id||(!lane&&closedLanes.has(value.id)))return fail();if(!lane&&value.type!==1)return fail();if(!lane){lane={id:value.id,pending:[],bytes:0,items:0,socket:null,timer:0,opened:false,localClosed:false,remoteClosed:false,finished:false};lanes.set(value.id,lane)}if(value.type===3&&!lane.opened)return finishLane(lane,false);if(lane.bytes+value.data.byteLength>laneQueueLimit||lane.items>=laneItemLimit||laneBuffered()+value.data.byteLength>queueLimit)return fail();lane.pending.push(value.data);lane.bytes+=value.data.byteLength;lane.items++;if(value.type===3)lane.localClosed=true;if(!lane.socket)openLane(lane);else runLaneUp(lane)}
function runLaneUp(lane){const socket=lane.socket;if(closed||lane.finished||!socket||socket.readyState!==WebSocket.OPEN||!lane.pending.length)return;if(socket.bufferedAmount>=batchLimit){if(!lane.timer)lane.timer=setTimeout(()=>{lane.timer=0;runLaneUp(lane)},10);return}let total=0,count=0;while(count<lane.pending.length&&count<batchFrames){const size=lane.pending[count].byteLength;if(count&&total+size>batchLimit)break;total+=size;count++}let body;if(count===1)body=lane.pending[0];else{const joined=new Uint8Array(total);let offset=0;for(let index=0;index<count;index++){joined.set(new Uint8Array(lane.pending[index]),offset);offset+=lane.pending[index].byteLength}body=joined.buffer}lane.pending.splice(0,count);lane.bytes-=total;lane.items-=count;try{socket.send(body)}catch{return fail()}port.postMessage({t:'traffic',up:total,down:0});if(lane.pending.length)queueMicrotask(()=>runLaneUp(lane))}
function countFrames(value){const view=new DataView(value);let offset=0,count=0;while(offset+8<=value.byteLength){offset+=8+view.getUint32(offset+4);count++}return count}
function send(value){if(carrierMode==='websocket-lanes'&&sessionToken){let values;try{values=splitFrames(value)}catch{return fail()}for(const item of values){if(item.id===0)continue;queueLane(item);if(closed)return}return}const buffered=socket&&socket.readyState===WebSocket.OPEN?socket.bufferedAmount:0;if(buffered+queuedBytes+value.byteLength>queueLimit)return fail();queued.push(value);queuedBytes+=value.byteLength;flushUp()}
function flushUp(){if(closed||!socket||socket.readyState!==WebSocket.OPEN||!queued.length)return;if(socket.bufferedAmount>=coalesceAt){if(!upTimer)upTimer=setTimeout(()=>{upTimer=0;flushUp()},10);return}let total=0,frames=0,count=0;while(count<queued.length){const size=queued[count].byteLength,n=countFrames(queued[count]);if(count&&(total+size>batchLimit||frames+n>batchFrames))break;total+=size;frames+=n;count++}let body;if(count===1)body=queued[0];else{const joined=new Uint8Array(total);let offset=0;for(let index=0;index<count;index++){joined.set(new Uint8Array(queued[index]),offset);offset+=queued[index].byteLength}body=joined.buffer}queued.splice(0,count);queuedBytes-=total;try{socket.send(body)}catch{return fail()}port.postMessage({t:'traffic',up:total,down:0});if(queued.length)queueMicrotask(flushUp)}
function relayBatch(value){const view=new DataView(value);let offset=0,frames=0,hasPing=false;while(offset<value.byteLength){if(value.byteLength-offset<8||frames++>=4096)return fail();const type=view.getUint8(offset),streamId=(view.getUint8(offset+1)<<16)|(view.getUint8(offset+2)<<8)|view.getUint8(offset+3),size=view.getUint32(offset+4),end=offset+8+size;if(size>1048576||end>value.byteLength)return fail();if(type===5&&streamId===0)hasPing=true;offset=end}if(offset!==value.byteLength)return fail();if(!hasPing){port.postMessage({t:'traffic',up:0,down:value.byteLength});port.postMessage(value,[value]);return}offset=0;while(offset<value.byteLength){const type=view.getUint8(offset),streamId=(view.getUint8(offset+1)<<16)|(view.getUint8(offset+2)<<8)|view.getUint8(offset+3),end=offset+8+view.getUint32(offset+4);if(type===5&&streamId===0){const pong=new Uint8Array(value.slice(offset,end));pong[0]=6;send(pong.buffer)}else{const frame=value.slice(offset,end);port.postMessage({t:'traffic',up:0,down:frame.byteLength});port.postMessage(frame,[frame])}offset=end}}
async function create(first){try{status('connecting');const response=await fetch(relayOrigin+'/api/v1/session',opts('POST',bootstrap,first));if(response.status!==200||response.headers.get('X-Carrier-Mode')!==carrierMode)throw 0;sessionToken=response.headers.get('X-Session-Token')||'';if(!sessionToken)throw 0;const welcome=await response.arrayBuffer();if(carrierMode==='websocket-lanes'){if(closed)return;port.postMessage(welcome,[welcome]);status('connected');const early=queued.splice(0);queuedBytes=0;for(const value of early){send(value);if(closed)return}return}socket=new WebSocket(relayOrigin.replace(/^https:/,'wss:')+'/api/v1/ws','tproxy-v1.'+sessionToken);socket.binaryType='arraybuffer';socket.onmessage=event=>{if(!(event.data instanceof ArrayBuffer)||!event.data.byteLength)return fail();relayBatch(event.data)};socket.onclose=()=>{if(!closed)fail()};socket.onerror=()=>{};socket.onopen=()=>{if(closed)return socket.close();port.postMessage(welcome,[welcome]);status('connected');flushUp()}}catch{fail()}}
function shutdown(notify){if(closed)return;closed=true;if(upTimer)clearTimeout(upTimer);for(const lane of lanes.values()){if(lane.timer)clearTimeout(lane.timer);if(lane.socket)try{lane.socket.close()}catch{}}lanes.clear();if(socket)try{socket.close()}catch{};if(notify&&sessionToken)fetch(relayOrigin+'/api/v1/session',opts('DELETE',sessionToken,null,true)).catch(()=>{});if(port)port.close()}
function activate(next){initialized=true;port=next;port.onmessage=event=>{const value=event.data;if(value instanceof ArrayBuffer){if(!creating){creating=true;create(value)}else send(value)}else if(value&&value.t==='close')shutdown(true)};port.start();status('connecting')}
addEventListener('message',event=>{if(initialized||event.source!==parent||!event.data||typeof event.data!=='object'||event.data.t!=='tproxy-init'||event.data.v!==1||event.ports.length!==1)return;let source;try{source=new URL(event.origin)}catch{return}if(source.protocol!=='http:'||source.hostname!=='127.0.0.1'||!source.port||source.origin!==event.origin)return;activate(event.ports[0])});
const native=globalThis.TelegramWebProxy;if(!initialized&&androidNonce&&native&&typeof native.postMessage==='function'){const direct={onmessage:null,start(){},close(){native.onmessage=null},postMessage(value){if(value instanceof ArrayBuffer){try{for(const frame of splitFrames(value))native.postMessage(frame)}catch{return fail()}}else native.postMessage(JSON.stringify(value))}};native.onmessage=event=>{let data=event.data;if(typeof data==='string'){try{data=JSON.parse(data)}catch{return}}if(direct.onmessage)direct.onmessage({data})};activate(direct);native.postMessage(JSON.stringify({t:'tproxy-android-init',v:1,nonce:androidNonce}))}
addEventListener('pagehide',()=>shutdown(true),{once:true});})();
</script></body></html>`;
  return new Response(body, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'Referrer-Policy': 'no-referrer',
      'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'Permissions-Policy': PERMISSIONS_POLICY,
      'Content-Security-Policy': `default-src 'none'; base-uri 'none'; child-src 'none'; connect-src 'self' wss://${hostname}; font-src 'none'; form-action 'none'; frame-ancestors http://127.0.0.1:*; frame-src 'none'; img-src 'none'; manifest-src 'none'; media-src 'none'; object-src 'none'; script-src 'nonce-${nonce}'; style-src 'none'; worker-src 'none'; sandbox allow-same-origin allow-scripts`
    }
  });
}
