import { base64Url } from './capability';

const PERMISSIONS_POLICY = 'accelerometer=(), autoplay=(), camera=(), clipboard-read=(), clipboard-write=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-create=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), web-share=(), xr-spatial-tracking=()';

export function bridgeResponse(hostname: string, bootstrapToken: string): Response {
  const nonce = base64Url(crypto.getRandomValues(new Uint8Array(18)));
  const origin = `https://${hostname}`;
  const body = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connection</title></head><body><script nonce="${nonce}">
(()=>{'use strict';const relayOrigin=${JSON.stringify(origin)};const bootstrap=${JSON.stringify(bootstrapToken)};const carrierMode="websocket";
const fragment=location.hash,androidNonce=/^#android=([A-Za-z0-9_-]{43})$/.exec(fragment)?.[1]||'';history.replaceState(null,'',location.pathname);
let initialized=false,closed=false,port=null,sessionToken='',socket=null,creating=false;const queued=[];let queuedBytes=0,upTimer=0;const queueLimit=33554432,batchLimit=524288,batchFrames=4096,coalesceAt=262144;
function splitFrames(value){const view=new DataView(value);let offset=0,result=[];while(offset<value.byteLength){if(value.byteLength-offset<8||result.length>=4096)throw 0;const size=view.getUint32(offset+4),end=offset+8+size;if(size>1048576||end>value.byteLength)throw 0;result.push(value.slice(offset,end));offset=end}if(!result.length)throw 0;return result}
const status=state=>{if(port&&!closed)port.postMessage({t:'status',state})};
const opts=(method,token,body,keepalive=false)=>({method,body,keepalive,mode:'same-origin',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:Object.assign(token?{Authorization:'Bearer '+token}:{},body?{'Content-Type':'application/octet-stream'}:{})});
function fail(){if(closed)return;status('failed');if(port)port.postMessage({t:'close'});shutdown(true)}
function countFrames(value){const view=new DataView(value);let offset=0,count=0;while(offset+8<=value.byteLength){offset+=8+view.getUint32(offset+4);count++}return count}
function send(value){const buffered=socket&&socket.readyState===WebSocket.OPEN?socket.bufferedAmount:0;if(buffered+queuedBytes+value.byteLength>queueLimit)return fail();queued.push(value);queuedBytes+=value.byteLength;flushUp()}
function flushUp(){if(closed||!socket||socket.readyState!==WebSocket.OPEN||!queued.length)return;if(socket.bufferedAmount>=coalesceAt){if(!upTimer)upTimer=setTimeout(()=>{upTimer=0;flushUp()},10);return}let total=0,frames=0,count=0;while(count<queued.length){const size=queued[count].byteLength,n=countFrames(queued[count]);if(count&&(total+size>batchLimit||frames+n>batchFrames))break;total+=size;frames+=n;count++}let body;if(count===1)body=queued[0];else{const joined=new Uint8Array(total);let offset=0;for(let index=0;index<count;index++){joined.set(new Uint8Array(queued[index]),offset);offset+=queued[index].byteLength}body=joined.buffer}queued.splice(0,count);queuedBytes-=total;try{socket.send(body)}catch{return fail()}port.postMessage({t:'traffic',up:total,down:0});if(queued.length)queueMicrotask(flushUp)}
function relayBatch(value){const view=new DataView(value);let offset=0,frames=0,hasPing=false;while(offset<value.byteLength){if(value.byteLength-offset<8||frames++>=4096)return fail();const type=view.getUint8(offset),streamId=(view.getUint8(offset+1)<<16)|(view.getUint8(offset+2)<<8)|view.getUint8(offset+3),size=view.getUint32(offset+4),end=offset+8+size;if(size>1048576||end>value.byteLength)return fail();if(type===5&&streamId===0)hasPing=true;offset=end}if(offset!==value.byteLength)return fail();if(!hasPing){port.postMessage({t:'traffic',up:0,down:value.byteLength});port.postMessage(value,[value]);return}offset=0;while(offset<value.byteLength){const type=view.getUint8(offset),streamId=(view.getUint8(offset+1)<<16)|(view.getUint8(offset+2)<<8)|view.getUint8(offset+3),end=offset+8+view.getUint32(offset+4);if(type===5&&streamId===0){const pong=new Uint8Array(value.slice(offset,end));pong[0]=6;send(pong.buffer)}else{const frame=value.slice(offset,end);port.postMessage({t:'traffic',up:0,down:frame.byteLength});port.postMessage(frame,[frame])}offset=end}}
async function create(first){try{status('connecting');const response=await fetch(relayOrigin+'/api/v1/session',opts('POST',bootstrap,first));if(response.status!==200||response.headers.get('X-Carrier-Mode')!==carrierMode)throw 0;sessionToken=response.headers.get('X-Session-Token')||'';if(!sessionToken)throw 0;const welcome=await response.arrayBuffer();socket=new WebSocket(relayOrigin.replace(/^https:/,'wss:')+'/api/v1/ws','tproxy-v1.'+sessionToken);socket.binaryType='arraybuffer';socket.onmessage=event=>{if(!(event.data instanceof ArrayBuffer)||!event.data.byteLength)return fail();relayBatch(event.data)};socket.onclose=()=>{if(!closed)fail()};socket.onerror=()=>{};socket.onopen=()=>{if(closed)return socket.close();port.postMessage(welcome,[welcome]);status('connected');flushUp()}}catch{fail()}}
function shutdown(notify){if(closed)return;closed=true;if(upTimer)clearTimeout(upTimer);if(socket)try{socket.close()}catch{};if(notify&&sessionToken)fetch(relayOrigin+'/api/v1/session',opts('DELETE',sessionToken,null,true)).catch(()=>{});if(port)port.close()}
function activate(next){initialized=true;port=next;port.onmessage=event=>{const value=event.data;if(value instanceof ArrayBuffer){if(!creating){creating=true;create(value)}else send(value)}else if(value&&value.t==='close')shutdown(true)};port.start();status('connecting')}
addEventListener('message',event=>{if(initialized||event.source!==parent||!event.data||typeof event.data!=='object'||event.data.t!=='tproxy-init'||event.data.v!==1||event.ports.length!==1)return;let source;try{source=new URL(event.origin)}catch{return}if(source.protocol!=='http:'||source.hostname!=='127.0.0.1'||!source.port||source.origin!==event.origin)return;activate(event.ports[0])});
const native=globalThis.TelegramWebProxy;if(!initialized&&androidNonce&&native&&typeof native.postMessage==='function'){const direct={onmessage:null,start(){},close(){native.onmessage=null},postMessage(value){if(value instanceof ArrayBuffer){try{for(const frame of splitFrames(value))native.postMessage(frame)}catch{return fail()}}else native.postMessage(JSON.stringify(value))}};native.onmessage=event=>{let data=event.data;if(typeof data==='string'){try{data=JSON.parse(data)}catch{return}}if(direct.onmessage)direct.onmessage({data})};activate(direct);native.postMessage(JSON.stringify({t:'tproxy-android-init',v:1,nonce:androidNonce}))}
addEventListener('pagehide',()=>shutdown(true),{once:true});})();
</script></body></html>`;
  return new Response(body, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'Referrer-Policy': 'no-referrer',
      'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'Permissions-Policy': PERMISSIONS_POLICY,
      'Content-Security-Policy': `default-src 'none'; base-uri 'none'; child-src 'none'; connect-src 'self' wss://${hostname}; font-src 'none'; form-action 'none'; frame-ancestors http://127.0.0.1:*; frame-src 'none'; img-src 'none'; manifest-src 'none'; media-src 'none'; object-src 'none'; script-src 'nonce-${nonce}'; style-src 'none'; worker-src 'none'; sandbox allow-same-origin allow-scripts`
    }
  });
}
